# Generated by Django 6.0 on 2025-12-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('oficial', 'Dólar Oficial'), ('blue', 'Dólar Blue'), ('mep', 'Dólar MEP'), ('ccl', 'Dólar CCL')], help_text='Tipo de cotización del dólar', max_length=20)),
                ('fecha', models.DateField(help_text='Fecha de la cotización')),
                ('compra', models.DecimalField(decimal_places=2, help_text='Precio de compra en ARS', max_digits=10)),
                ('venta', models.DecimalField(decimal_places=2, help_text='Precio de venta en ARS', max_digits=10)),
                ('actualizado', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
            ],
            options={
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha', 'tipo'],
                'indexes': [models.Index(fields=['fecha'], name='dashboard_c_fecha_c7a7fd_idx'), models.Index(fields=['tipo', 'fecha'], name='dashboard_c_tipo_ba2e5f_idx')],
                'unique_together': {('tipo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='IndiceEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inflacion', 'Inflación Mensual'), ('tasa', 'Tasa de Interés BCRA'), ('reservas', 'Reservas Internacionales'), ('riesgo_pais', 'Riesgo País'), ('merval', 'Índice Merval')], help_text='Tipo de índice económico', max_length=20)),
                ('fecha', models.DateField(help_text='Fecha del índice')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor del índice', max_digits=15)),
                ('unidad', models.CharField(help_text='Unidad de medida (ej: %, Millones USD, puntos)', max_length=50)),
                ('actualizado', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
            ],
            options={
                'verbose_name_plural': 'Índices Económicos',
                'ordering': ['-fecha', 'tipo'],
                'indexes': [models.Index(fields=['fecha'], name='dashboard_i_fecha_2fcc93_idx'), models.Index(fields=['tipo', 'fecha'], name='dashboard_i_tipo_2b8fdb_idx')],
                'unique_together': {('tipo', 'fecha')},
            },
        ),
    ]
