# Generated by Django 6.0 on 2025-12-30 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionInternacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(help_text='Simbolo de la accion (ej: AAPL, MSFT)', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre completo de la empresa/fondo', max_length=200)),
                ('tipo', models.CharField(choices=[('accion', 'Accion'), ('etf', 'ETF'), ('indice', 'Índice')], default='accion', max_length=10)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion del activo', null=True)),
                ('sector', models.CharField(blank=True, help_text='Sector económico', max_length=100, null=True)),
                ('moneda', models.CharField(default='USD', help_text='Moneda de cotización', max_length=10)),
                ('activo', models.BooleanField(default=True, help_text='Indica si sigue activo en el mercado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acción Internacional',
                'verbose_name_plural': 'Acciones Internacionales',
                'ordering': ['simbolo'],
                'indexes': [models.Index(fields=['simbolo'], name='dashboard_a_simbolo_0170e1_idx'), models.Index(fields=['tipo', 'activo'], name='dashboard_a_tipo_6a0806_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de cálculo')),
                ('periodo', models.CharField(choices=[('D', 'Diario'), ('W', 'Semanal'), ('M', 'Mensual')], default='D', max_length=1)),
                ('retorno', models.FloatField(help_text='Retorno porcentual')),
                ('volatilidad', models.FloatField(help_text='Volatilidad (desviación estándar)')),
                ('volumen_promedio', models.FloatField(help_text='Volumen promedio')),
                ('rsi', models.FloatField(blank=True, help_text='Relative Strength Index (14 periodos)', null=True)),
                ('media_movil_20', models.FloatField(blank=True, help_text='Media móvil 20 días', null=True)),
                ('media_movil_50', models.FloatField(blank=True, help_text='Media móvil 50 días', null=True)),
                ('maximo_52_semanas', models.FloatField(blank=True, null=True)),
                ('minimo_52_semanas', models.FloatField(blank=True, null=True)),
                ('correlacion_dolar_blue', models.FloatField(blank=True, help_text='Correlación con dólar blue', null=True)),
                ('calculado', models.DateTimeField(auto_now=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='dashboard.accioninternacional')),
            ],
            options={
                'verbose_name': 'Métrica de Acción',
                'verbose_name_plural': 'Métricas de Acciones',
                'ordering': ['-fecha', 'accion'],
                'unique_together': {('accion', 'fecha', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='PrecioAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del precio')),
                ('apertura', models.DecimalField(decimal_places=4, help_text='Precio de apertura', max_digits=12)),
                ('maximo', models.DecimalField(decimal_places=4, help_text='Precio máximo del día', max_digits=12)),
                ('minimo', models.DecimalField(decimal_places=4, help_text='Precio mínimo del día', max_digits=12)),
                ('cierre', models.DecimalField(decimal_places=4, help_text='Precio de cierre', max_digits=12)),
                ('cierre_ajustado', models.DecimalField(decimal_places=4, help_text='Precio de cierre ajustado por splits/dividendos', max_digits=12)),
                ('volumen', models.BigIntegerField(help_text='Volumen negociado')),
                ('dividendo', models.DecimalField(decimal_places=4, default=0, help_text='Dividendo pagado', max_digits=10)),
                ('split', models.DecimalField(decimal_places=4, default=1, help_text='Coeficiente de split', max_digits=10)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='dashboard.accioninternacional')),
            ],
            options={
                'verbose_name': 'Precio de Acción',
                'verbose_name_plural': 'Precios de Acciones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='dashboard_p_fecha_4136af_idx'), models.Index(fields=['accion', 'fecha'], name='dashboard_p_accion__5fd2f5_idx')],
                'unique_together': {('accion', 'fecha')},
            },
        ),
    ]
