# Generated by Django 6.0 on 2025-12-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_accioninternacional_metricaaccion_precioaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='accioninternacional',
            name='pais',
            field=models.CharField(default='USA', help_text='País de origen', max_length=50),
        ),
        migrations.AlterField(
            model_name='accioninternacional',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del activo', null=True),
        ),
        migrations.AlterField(
            model_name='accioninternacional',
            name='simbolo',
            field=models.CharField(help_text='Símbolo de la acción (ej: AAPL, MSFT)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='accioninternacional',
            name='tipo',
            field=models.CharField(choices=[('accion', 'Acción'), ('etf', 'ETF'), ('indice', 'Índice')], default='accion', max_length=10),
        ),
    ]
